### ISSUE TITLE
AutorecoveringConnection prints TopologyRecoveryException to console

### ISSUE THREAD

**Issue by JonAnders** [rabbitmq/rabbitmq-dotnet-client#254] opened 2016-09-06 20:48 UTC
When a connection has successfully recovered, a TopologyRecoveryException is printed to the console if no channel is currently open.

This is somewhat related to #233, but I believe this exception should never occur in the first place, so it's not a duplicate of #94 or #132.

Conditions for the bug to appear:
- AutomaticRecoveryEnabled = true
- No channels are open
- The recovering connection has had at least one channel open earlier
- Tested on client v4.0.2 and server v3.6.5

Steps to reproduce:
1. Run the attached code.
2. When "Press [enter] to exit." appears, restart the RabbitMQ server to simulate a network error. Note that this is after the channel has been disposed, but before the connection is disposed.
3. Wait for the server to restart.
4. When the server is up again and the connection has recovered, watch this exception appear in the console window:

```
Topology recovery exception: RabbitMQ.Client.TopologyRecoveryException: Caught an exception while recovering queue hello: Already closed: The AMQP operation was interrupted: AMQP close-reason, initiated by Application, code=200, text="Goodbye", classId=0, methodId=0, cause= ---> RabbitMQ.Client.Exceptions.AlreadyClosedException: Already closed: The AMQP operation was interrupted: AMQP close-reason, initiated by Application, code=200, text="Goodbye", classId=0, methodId=0, cause=
   at RabbitMQ.Client.Impl.SessionBase.Transmit(Command cmd)
   at RabbitMQ.Client.Impl.ModelBase.ModelSend(MethodBase method, ContentHeaderBase header, Byte[] body)
   at RabbitMQ.Client.Framing.Impl.Model._Private_QueueDeclare(String queue, Boolean passive, Boolean durable, Boolean exclusive, Boolean autoDelete, Boolean nowait, IDictionary`2 arguments)
   at RabbitMQ.Client.Impl.ModelBase.QueueDeclare(String queue, Boolean passive, Boolean durable, Boolean exclusive, Boolean autoDelete, IDictionary`2 arguments)
   at RabbitMQ.Client.Impl.ModelBase.QueueDeclare(String queue, Boolean durable, Boolean exclusive, Boolean autoDelete, IDictionary`2 arguments)
   at RabbitMQ.Client.Impl.RecordedQueue.Recover()
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.RecoverQueues()
   --- End of inner exception stack trace ---
```

Interesting observations:
- Despite the exception, the connection is successfully recovered and new channels may be opened.
- If no channels has ever been opened on the recovering connection, no exception is printed.

Code:

``` C#
using System;
using RabbitMQ.Client;

namespace Bug
{
    class Program
    {
        static void Main(string[] args)
        {
            var factory = new ConnectionFactory()
            {
                HostName = "localhost",
                AutomaticRecoveryEnabled = true
            };
            using (var connection = factory.CreateConnection())
            {
                using (var channel = connection.CreateModel())
                {
                    channel.QueueDeclare(
                        queue: "hello",
                        durable: false,
                        exclusive: false,
                        autoDelete: false,
                        arguments: null);
                }

                Console.WriteLine("Press [enter] to exit.");
                Console.ReadLine();
            }
        }
    }
}
```

**Comment by michaelklishin** [comment] 2016-09-06 20:52
It is not possible for a client library to guarantee there will be no exceptions during recovery. All kinds of things can go wrong right when a recovery is in progress. Perhaps in this particular case something can be improved but if recovery eventually succeeds, I'm not sure this issue can justify the amount of time investigating what exactly is going on might take.

**Comment by JonAnders** [comment] 2016-09-06 21:33
I absolutely agree that there always will be things that can go wrong during recovery. This particular exception is something that happens consistently every single time though.

I think it looks bad to print out an exception when things work. It took me a while to understand that everything was actually working. But I can understand that fixing this might have a low priority.

**Comment by kjnilsson** [comment] 2016-10-14 16:57
Related issue: https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/267

If this was implemented the `Console.WriteLog`s would be replaced with some kind of logging abstraction (none by default).

**Comment by michaelklishin** [comment] 2016-11-07 10:08
The original issue for a logging abstraction is #94.

**Comment by svrx** [comment] 2017-04-25 10:39
I have experienced this issue and I totally disagree it is just a usability bug related to lack of proper logging integration.

According to my investigation this issue is a functional bug in the topology auto recovering model.

In short, if an Entity (Queue, Exchange, ...) is declared in a channel that gets closed by the time a failure happens, the declare Entities will fail to be recovered. 
In most cases this is not to critical, because consumers channels are usually open for as long we want consumption to occur (likely the lifetime of the application). 
But it becomes critical when non durable objects are used, since in that case the subscriptions will become silently stale.

**Comment by michaelklishin** [comment] 2017-04-25 10:51
@svrx did your investigation include looking at the code? If so, can you post links to the relevant lines in `AutorecoveringConnection` and `AutorecoveringModel`? That's where all the topology recovery logic resides.

Topology recovery depends on a cache of known entities. When it's time to invalidate that cache is a fairly involved question and not everyone has the same opinion on it, so please provide the specifics:

 * A code snippet that demonstrates what your investigation was about
 * How exactly the channel was closed
 * Source code links

and anything else that's relevant.

**Comment by svrx** [comment] 2017-04-25 11:44
Yes, source code was built locally, debugged step by step and analysed.

The problem is not very evident looking at existing code, because the issue is more about the code that's missing than the code that is there.

Essentially, as you know, `AutorecoveringConnection` and `AutorecoveringModel` work by wrapping a real Connection and Model, so the internal reference can be replaced without changing the reference handed to external code (consumers).

Topology recovering will work on the same assumption, some recorded entities will hold a reference to the channel they were declared on. 

From `RecordedQueue`:
```csharp
...
public void Recover()
{
    QueueDeclareOk ok = ModelDelegate.QueueDeclare(NameToUseForRecovery, durable,
        exclusive, IsAutoDelete,
        arguments);
    Name = ok.QueueName;
}
...
```
When recovery happens internal channels will be recovered, but only the ones still open.
The problem is that meanwhile you have references in recorded entities, such as Queues, that will never be recovered, because they have been unregistered from the connection when closed.

I'm working on a fix for that at the moment and plan to submit a pull request, later today.
My idea for the fix is when recovering entities, if the channel they were using is closed, I'll create one just for the recovery to run.

Please let me know your thoughts or if you need more details.

**Comment by michaelklishin** [comment] 2017-04-25 12:19
@svrx are you suggesting that we recover stuff on closed channels or even connections, too? I would really like a few more people to share their opinion before you spend any time on any pull requests.

@kjnilsson @bording @danielmarbach do you have an opinion on the above?

**Comment by michaelklishin** [comment] 2017-04-25 12:23
For example, semantically recovering an exclusive queue on a closed connection makes no sense.

I suspect that this client uses the same recovery logic as the Java one, which adopted it from Bunny, which adopted it from the very first Ruby client, the amqp gem. Which makes it 6 or so years old by now and I recall only one topology recovery logic change in that period of time: when porting it to the Java client, we had to make caching connection-wide to avoid cases where you declare something on one channel, then delete it on another one it would suddenly re-appear after recovery.

So yeah, I'm not sold on the idea that this is a functional bug. This is a functional matter of opinion.

**Comment by kjnilsson** [comment] 2017-04-25 12:46
I agree recovering an explicitly closed channel during recovery sounds wrong. Surely when closing the channel the expectation is that consumers using that channel will stop? 

I can reproduce the error by setting up a consumer, stopping RabbitMQ, closing the channel then restarting RabbitMQ. In fact it happens even if I close the channel before stopping RabbitMQ (Which arguably isn't ideal but doesn't really cause a problem).

What I cannot comprehend is when an application would expect consumers for an explicitly closed channel to recover.

**Comment by svrx** [comment] 2017-04-25 13:27
Hmm... 
I don't think you've understood the problem correctly.
I agreed that Consumers on closed channels should not be recovered, as they wouldn't be functioning without the channel.
On the other side, once you declare a Queue, for example, it will live for longer than the channel it was created on. 

I believe that any topology entity with longer lifetime than the channel it's declared on, should be recovered regardless of the original channel being around or not. 
This is not a major issue because the broker persists the objects declared, unless they are not durable or there is some conflict related to network partitions for example, in which case the recoverability expectation is broken.

There are work-arounds, but I don't think it should be a requirement for the topology to be declared on the same channel that the consumer are running on.

The exclusive queues I believe they are handled on exceptional basis already. 
The recorded entities should reflect the active state required before the connection dropped. Hence it should be far assumption that all those entities required should be recovered after a failure, which is exactly my suggestion to fix it.

Recovering recorded topology entities (Exchanges, Queues and Bindings) declared on the connection, regardless of the channel they were declared on. (not consumers, event handlers or channels)

Does this change you perspective on the issue?

**Comment by svrx** [comment] 2017-04-25 13:38
@kjnilsson it causes a problem, try making your Queue non-durable for example. 
It breaks recoverability expectations.

**Comment by kjnilsson** [comment] 2017-04-25 14:05
I see what you mean, I am still not sure _non-durable_ queues (+bindings and exchanges) should be recovered. If the disconnection was caused by a network issue they will still be there when reconnection occurs. If they were lost due to the node being restarted they behave consistently with non-durable semantics. If you want an entity to survive a restart you have to make them durable.

What are the scenarios where you need a specific connection to ensure the existence of a non-durable RabbitMQ entity?

**Comment by svrx** [comment] 2017-04-25 14:37
Non-durable queues/exchanges, if used it's accepted you don't care to persist those to disk, from the broker point of view.
From the consuming application point of view, the subscription should still be valid, because you never know when producer application will come back, so if you don't recover those on recovery of the connection, you'll get into a race condition and depending which party comes back first (producer or consumer) you may get different results.

The choice on this one is either that acknowledged and addressed or accept the broken recoverability expectation which is prone to race condition behaviour.

**Comment by svrx** [comment] 2017-04-25 15:00
I know this will not happen very often, it was actually found while testing cluster disaster recovery. But it can indeed happen.

**Comment by kjnilsson** [comment] 2017-04-25 15:28
It feels to me you are trying to work around an issue that could be solved by using durable entities or have each consumer declare the non-durable topology. For the latter yes you could still have a race where a producer publishes a message to an exchange with no bindings after a broker restart. However, that is what durable entities are for.  I don't see how your proposed change would address that either.

Can you explain what the race condition is that your change would solve?

**Comment by michaelklishin** [comment] 2017-04-25 16:23
The point of topology recovery is not to make entities survive server restart. It is also by definition somewhat opinionated because it relies on caching of performed library operations and cache invalidation is problem with more than one correction solution (depending on who you ask).

At this point we've established that there is no obvious "functional bug" in topology recovery and switching to durable entities would largely or entirely eliminate the problem.

Feel free to look into a PR if you have the time to spend but we do not guarantee that it will be merged as two of our team members see the proposed solution as a way to reinvent durable entities.

The rest of this discussion belongs to rabbitmq-users (if there's anything left to discuss at all).

**Comment by lukebakken** [comment] 2020-03-14 23:45
No movement in almost three years, closing.

**Closed by lukebakken** 2020-03-14 23:45 UTC
Labels: usability, wontfix
