### ISSUE TITLE
Consumer tags aren't cleaned on channel close causing memory leak.

### ISSUE THREAD

**Issue by foxthedream** [rabbitmq/rabbitmq-dotnet-client#1302] opened 2023-02-20 08:51 UTC
RabbitMQ Client Library Version: C# 6.4
RabbitMQ Server Version: NA
Erlang Version: NA
Operating System: NA
RabbitMQ Plugins: NA

We are using pooling to keep 20 connections open to RabbitMQ server. Those 20 connections are used to open channels and to start consumers. We can have from 500 to 1000 consumers spread across those 20 connections. Most of them idle. We open a new channel and consumer to Rabbit MQ when one of our customers opens a new TCP connection to us. When they disconnect from us we in turn disconnect from Rabbit MQ server. Some of our customers regularly drop the connection and reconnect, every 10 to 15 minutes. This causes us to open and close thousands of channels a day.

When a new consumer is created, the call to RecordConsumer on the AutorecoveringConnection adds the consumer tag to an internal dictionary of consumer tags and RecordedConsumers. The item that is added can only be cleared out via the DeleteRecordedConsumer method which in turn is only called via a BasicCancel or BasicCancelNoWait. Simply closing the channel is not sufficient.

In our case, after running for a week we had over 53 000 RecordedConsumer objects. We took process dumps and analyzed the dumps for the memory leak.

**Comment by michaelklishin** [comment] 2023-02-20 10:39
Not sure how reliable is [`Dispose`](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/85c53be64bd4e3b6e123b951669493438d8fa108/projects/RabbitMQ.Client/client/impl/AutorecoveringModel.cs#L201) for this kind of thing, if not, connection's method that closes the
channel can be altered to clean up those dependent objects from the map.

Or a weak reference map can be used for that specific collection.

You are welcome to submit a PR :)

**Comment by lukebakken** [comment] 2023-02-20 23:19
Like @michaelklishin said a PR to fix this issue would be welcome.

**Comment by lukebakken** [comment] 2023-03-20 22:58
@foxthedream since you can reproduce this issue and verify a fix, please test out the branch in this PR - https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/1317

Thank you!

**Comment by lukebakken** [comment] 2023-03-21 14:03
@foxthedream for the time being you will have to cancel your consumers correctly.

The fix for this issue isn't trivial because the recorded consumers in the connection are used for recovery. When a channel (model) closes, we can't just remove them at that point, because that would also remove the recorded consumers if the channel is closed due to an error and must be recovered.

**Comment by lukebakken** [comment] 2023-03-21 15:23
@foxthedream please give this branch a try: [link](https://github.com/rabbitmq/rabbitmq-dotnet-client/tree/rabbitmq-dotnet-client-1302)

**Comment by foxthedream** [comment] 2023-03-23 08:26
Hi Luke

At the moment I am working on another project. I will give it a try as soon
as we circle back to this. But I am unsure when I will have capacity. Could
be in 2 or 3 weeks.

Regards,

**Closed as completed** 2023-03-23 13:49 UTC
