### ISSUE TITLE
Problem with SSL authentification on 3.6.2 .net client

### ISSUE THREAD

**Issue by MIVerTFT** [rabbitmq/rabbitmq-dotnet-client#211] opened 2016-06-20 13:47 UTC
Hi,
I have some problem with authentification on 3.6.2 .net client.
Server have config like that:
```
[
	{ssl, [{versions, ['tlsv1.2', 'tlsv1.1']}]},
	{rabbit, [

	        {log_levels, [{connection, info}, {channel, info}]},
		{auth_mechanisms,['EXTERNAL']},
		{ssl_listeners, [5671]},
		{ssl_options, [{cacertfile,"cacert.pem"},
				{certfile,"cert.pem"},
				{keyfile,"key.pem"},
				{verify,verify_peer},
				{fail_if_no_peer_cert,false}]},
		{auth_backends, [rabbit_auth_backend_internal]},
		{ssl_cert_login_from, common_name}
	]}
].
```

I try connecting with following code
```
var cf = new ConnectionFactory {HostName = "Host", Port = 5671};
cf.AuthMechanisms = new AuthMechanismFactory[]{new ExternalMechanismFactory()};
cf.Ssl.Certs = new X509CertificateCollection(new[] { GetCert() });
cf.Ssl.Enabled = true;
var connection = cf.CreateConnection();
```
And than catch exception with message {"No compatible authentication mechanism found - server offered []"}

But if I set AutomaticRecoveryEnabled property to true, it's work fine.

I think that the problem is in the method ConnectionFactory.CreateConnection(...) If AutomaticRecoveryEnabled set to false, create the endpoint is not set sll property. If I do so, the problem goes away.

```
public IConnection CreateConnection(IList<string> hostnames, String clientProvidedName)
        {
            IConnection conn;
            try
            {
                if (AutomaticRecoveryEnabled)
                {
                    var autorecoveringConnection = new AutorecoveringConnection(this, clientProvidedName);
                    autorecoveringConnection.Init(hostnames);
                    conn = autorecoveringConnection;
                }
                else
                {
                    IProtocol protocol = Protocols.DefaultProtocol;
                    var selectedHost = this.HostnameSelector.NextFrom(hostnames);
                    var endPoint = AmqpTcpEndpoint.Parse(selectedHost);
                    endPoint.Ssl = this.Endpoint.Ssl; // <------ set ssl property
                    conn = protocol.CreateConnection(this, false, CreateFrameHandler(endPoint), clientProvidedName);
                }
            }
            catch (Exception e)
            {
                throw new BrokerUnreachableException(e);
            }
            return conn;
        }
```

**Comment by michaelklishin** [comment] 2016-06-20 13:50
Possible duplicate of https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/186?

**Closed** 2016-06-20 14:41 UTC
