### ISSUE TITLE
CoreCLR port

### ISSUE THREAD

**Issue by ghost** [rabbitmq/rabbitmq-dotnet-client#148] opened 2015-12-29 15:33 UTC
Hey, 

Do you have any plans to port to CoreClr? Happy to help out if there is buy-in etc.

**Comment by michaelklishin** [comment] 2015-12-29 16:09
Duplicate of https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/103.

We already have a WinRT port which ended up reusing most of the code, so I'd be interested in seeing how difficult can it be to support CoreCLR.

**Comment by sblackler** [comment] 2015-12-29 17:09
I should have some free time over the weekend, so i'll pull down the code and have a go at porting it for you. Will report back with my findings.

**Comment by jeremymeng** [comment] 2016-01-09 04:57
@sblackler How is it going?  I attempted the port too as a hobby: https://github.com/rabbitmq/rabbitmq-dotnet-client/compare/master...jeremymeng:CoreClr.  Both client and unit test project build.  I attempted to run the tests but it seems like I don't have the `rabbitmqctl` so the test process crashed on me.  Anyway hope this is helpful to anyone who wants to continue working on it.

**Comment by michaelklishin** [comment] 2016-01-09 10:20
@jeremymeng thank you. If you can explain what kind of environment is necessary to give it a try (I have Windows 8.1), I can do it.

**Comment by michaelklishin** [comment] 2016-01-09 10:23
@jeremymeng the changes look smaller than I thought, this is encouraging. Note that I'm afraid we can't license parts as [MSPL](http://opensource.org/licenses/MS-PL) and to integrate your changes eventually we'd have to ask to you sign [our CA](https://github.com/rabbitmq/ca).

**Comment by jeremymeng** [comment] 2016-01-09 23:38
> thank you. If you can explain what kind of environment is necessary to give it a try (I have Windows 8.1), I can do it.

VS 2015 Community Editor with update 1 should be good.  For command-line only experience, you can install ASP.NET 5 RC as described at https://docs.asp.net/en/latest/getting-started/index.html

**Comment by theparticleman** [comment] 2016-01-12 17:36
@ru-sh has created a fork that targets CoreCLR that I've been using (he also has an unofficial NuGet package). It has a bug where trying to connect via IPv6 throws an unexpected exception type, so then it doesn't try connecting via IPv4. Once I fixed that it would connect from my Windows client host to my Rabbit running on my Linux Vagrant guest. But going from a Linux Vagrant client to Rabbit running on another Vagrant client hangs. Haven't gotten farther than that yet.

Here's a link to his fork: https://github.com/ru-sh/rabbitmq-dotnet-client/commit/ffedb324012f68824444004b6dbb43892f914786

**Comment by doc** [comment] 2016-03-26 00:03
Hey Guys, any updates on this port? Keen to see support for .net core arrive so happy to help in any way I can.

**Comment by michaelklishin** [comment] 2016-03-26 02:55
No updates besides that we've decided it should be a completely new client.

**Comment by michaelklishin** [comment] 2016-05-05 11:29
We've outlined our plan for the future of this client [on rabbitmq-users](https://groups.google.com/forum/#!topic/rabbitmq-users/iiric1i_OXs).

**Comment by michaelklishin** [comment] 2016-06-03 22:16
@jacksontbryan we can't prevent people from forking but it'd be a huge waste of time. We have a branch that works on CoreCLR but we cannot really test it beyond small F# scripts because the NUnit version we use doesn't run on CoreCLR. We'll try NUnit 3 or a different library but there is no guarantee that those work. Moving to a different testing framework is not a small task either.

I don't know what "real enterprise applications" means but the overall ecosystem migration to CoreCLR is far from being on the finish line, so "pretty big blocker" is a bit of an overstatement if you ask me (feel free to react with a 👎, this is what open source maintainers care about, right). And our little client barely has any dependencies to worry about.

Anyhow, I'm going to lock this as we do not use GitHub issues for discussions, reactions, and all that noise. If we can find a testing framework that works on CoreCLR today, there will be a branch of this client available as an interim step to the new client.

**Comment by kjnilsson** [comment] 2016-06-07 19:36
I've been working on this and have just about got it to pass the test suite. It needs a bit of tidying up and documentation needs to be updated but I should be ready to push a branch with dotnetcore support in the next couple of days or so. @doc @jacksontbryan are you up for doing a bit of testing when that happens?

**Comment by kjnilsson** [comment] 2016-06-08 15:05
ok I've now pushed a branch named `dotnetcore` that passes all tests. Please feel free to try it out and let me know how you get on. There are some instructions in `BUILDDOTNETCORE.md` of how to build it.

Please note this branch is largely unproven/untested and here for previewing purposes only at this stage.

**Comment by michaelklishin** [comment] 2016-06-08 15:07
@kjnilsson we should produce a binary build (and upload it to GitHub as a release plus post to the mailing list with an announcement)

**Closed** 2016-06-13 19:57 UTC
Labels: effort-high, enhancement

**Comment by michaelklishin** [comment] 2016-06-13 20:02
This client in master is now compatible with .NET Core (we have a .NET Core-based toolchain and all tests pass). We are planning to have a NuGet feed with master releases ready for public consumption soon. All credit for this work goes to @kjnilsson.

Note that this support *is* experimental at this point, both because .NET Core itself changes often and our understanding of how to best support .NET 4.5 and .NET Core (WinRT is not supported in master at the moment since we couldn't get the .NET Core build toolchain to work with WinRT).

The plan is to stabilize .NET Core support and then keep this client in maintenance mode (with .NET 4.5 and .NET Core being two supported targets) until a new client that exclusively targets .NET Core can be developed from scratch. That's why I think it's fair to close this issue. Please file new ones if you have suggestions about specific and actionable changes in master.

**Comment by vassilvk** [comment] 2016-06-14 12:34
Thank you @kjnilsson and @michaelklishin for prioritizing this!

**Comment by michaelklishin** [comment] 2016-06-30 13:00
Another update: as of #213 we target the most recent version of .NET Core available a.t.m.

**Comment by kjnilsson** [comment] 2016-07-01 09:33
Prereleases can be obtained from our AppVeyor NuGet feed: https://ci.appveyor.com/nuget/rabbitmq-dotnet-client-ci

**Comment by michaelklishin** [comment] 2018-06-01 05:52
FTR, theere is no need to use the AppVeyor NuGet feed above. 4.0 and later releases of this client are distributed using the [regular NuGet feed](https://www.nuget.org/packages/RabbitMQ.Client/) used by this library.
