### ISSUE TITLE
Heartbeat thread taking down process in .Net again

### ISSUE THREAD

**Issue by grrrrrrrrrrr** [rabbitmq/rabbitmq-dotnet-client#259] opened 2016-09-21 09:40 UTC
It seems in version 4.1 the heartbeat thread is crashing and taking down the rest of an application again in a way that can't really be handled client side. I think this is something that was fixed in 3.5. something previously and has come back.

**Comment by michaelklishin** [comment] 2016-09-21 09:57
@grrrrrrrrrrr I'm sorry but we cannot work with this much information. Either provide details (at exception stack trace, for example) or we'll have to close this.

**Comment by michaelklishin** [comment] 2016-09-21 09:58
If this is "something fixed in 3.5" then please provide a GitHub issue number, too.

**Comment by grrrrrrrrrrr** [comment] 2016-09-21 10:07
yeah yeah, stacktrace or GTFO. Here you go:

>    at System.Environment.get_StackTrace()
   at Magna.Impex.Workflow.Autofac.Service.ImpexServiceHost.Stop() in E:\BuildAgent\work\7215e63d8497f477\Magna.Impex.Workflow.Autofac\Service\ImpexServiceHost.cs:line 111
   at Topshelf.ServiceConfiguratorExtensions.<>c__DisplayClassa`1.<WhenStopped>b__9(T service, HostControl control)
   at Topshelf.Builders.DelegateServiceBuilder`1.DelegateServiceHandle.Stop(HostControl hostControl)
   at Topshelf.Runtime.Windows.WindowsServiceHost.OnStop()
   at System.ServiceProcess.ServiceBase.DeferredStop()
   at Topshelf.Runtime.Windows.WindowsServiceHost.CatchUnhandledException(Object sender, UnhandledExceptionEventArgs e)
   at RabbitMQ.Client.Framing.Impl.Connection.HeartbeatReadTimerCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

This is actually a stacktrace I stuck in for a topshelf windows service to see what was causing the services to stop, but it shows you most of the stuff you need to know I think.

**Comment by grrrrrrrrrrr** [comment] 2016-09-21 10:09
Also, the actual exception stacktrace is here

> System.NullReferenceException: Object reference not set to an instance of an object.
   at RabbitMQ.Client.Framing.Impl.Connection.HeartbeatReadTimerCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by grrrrrrrrrrr** [comment] 2016-09-21 10:09
I think its a similar issue to this: https://groups.google.com/forum/#!topic/rabbitmq-users/7zR-gQDU5pQ

**Comment by michaelklishin** [comment] 2016-09-21 10:10
This is very likely a duplicate of https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/257. So please give a pre-release version mentioned there a try.

**Closed by michaelklishin** 2016-09-21 10:10 UTC
Labels: no-decision

**Comment by grrrrrrrrrrr** [comment] 2016-09-21 10:16
OK thanks for your help, it does look very similar, will try that out
