### ISSUE TITLE
Handle Topology Recovery Exception

### ISSUE THREAD

**Issue by Greatsamps** [rabbitmq/rabbitmq-dotnet-client#233] opened 2016-08-06 07:10 UTC
We have been tracking an issue where sometimes some of our consumers are not able to automatically recover their topology. This happens very rarely and is solved by a connection restart, but the issue is that currently there is no way for our application to be notified that this has happened.

We simply see the fact that an exception has occurred written to the console, which given we have thousands of consumers is pretty difficult to manage. 

The method causing this is this one:

`protected void HandleTopologyRecoveryException(TopologyRecoveryException e)
 {
          Console.WriteLine("Topology recovery exception: {0}", e);
 }`

Would it be possible to attach an event to this so that the application can be notified if this has happened and we can then decide how to handle it?

**Comment by michaelklishin** [comment] 2016-08-06 17:10
This is a natural part of #94 and a duplicate of #132, if I understand the request correctly.

**Closed by michaelklishin** 2016-08-06 17:10 UTC
