### ISSUE TITLE
Migrate to dotnet core 1.1 project system

### ISSUE THREAD

**Issue by kjnilsson** [rabbitmq/rabbitmq-dotnet-client#308] opened 2017-02-16 12:14 UTC
Once dotnet core 1.1 is out of it's RC phase we need to migrate the project system. It may be worthwhile attempting this sooner to preempt any potential issues.

https://github.com/dotnet/core/tree/master/release-notes

**Comment by bording** [comment] 2017-02-16 19:25
@kjnilsson If you install the RC4 package, you can already use the new project system in VS Code. I've already migrated one of my side projects where I've been using the VS 2017 RC. I just tried running it under VS Code, and everything is working great.

It does look like the WinRT projects are going to have to be removed, because it doesn't look like VS 2017 is going to be supporting Win8 app development.

I'd be happy to submit a PR with the project migration changes.

**Comment by bording** [comment] 2017-02-16 19:33
@kjnilsson Actually, you might be interested in checking out the side project I mentioned above. I've started playing around with writing my own RabbitMQ client: https://github.com/bording/RabbitMQClient.

It's using the Pipelines stuff from the CoreFX Labs repo: https://github.com/dotnet/corefxlab

It's still super rough and doesn't really do any error checking yet, but I can already handle all/most of the Channel, Exchange, and Queue methods.

**Comment by kjnilsson** [comment] 2017-02-17 12:00
@bording thanks - did you test your migration on anything unix based? I get on this on osx post `dotnet migrate`:

```/usr/local/share/dotnet/sdk/1.0.0-rc4-004771/Microsoft.Common.CurrentVersion.targets(1111,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/knilsson/code/rabbitmq/rabbitmq-public-umbrella-master/deps/rabbitmq_dotnet_client/projects/client/RabbitMQ.Client/RabbitMQ.Client.csproj]
``` 

Looks like it isn't picking up the mono install as it used to before.

**Comment by bording** [comment] 2017-02-17 14:57
@kjnilsson Oh yeah, I forgot about how you're building stuff from unix. I haven't tried that yet. I'll give it a try and do some research to see if there's a solution.

**Comment by bording** [comment] 2017-02-18 04:09
I've spent some time looking into this, and the new tooling does currently have a regression where they are no longer pulling in mono to be able to build net451 from non-Windows machines. :cry:

dotnet/sdk/issues/335

I tried out the workaround mentioned [here](https://github.com/dotnet/sdk/issues/335#issuecomment-271186591), but I was getting errors about missing types that should have been there, so I'm guessing the targeting pack nuget is missing some things.

If Microsoft doesn't get this fixed for RTM, and based on the issue it doesn't look likely, then you'd need to either hold off moving to the new project system (and VS 2017), or consider dropping net451 and just compile for netstandard1.5. That would mean you'd be moving the minimum supported framework to 4.6.1, though. :cry:

Another thing that I ran into while playing around with this is that NUnit does not currently work in the new project system either, so you can't run tests from inside of VS 2017 or from the command line via `dotnet test`. 

nunit/nunit3-vs-adapter/issues/297

Looks like xUnit works just fine already, so maybe it's time to migrate? 😁

**Comment by kjnilsson** [comment] 2017-02-18 07:12
As I suspected then. :/ I'm sure nunit will get updated at some point.
We'll see about net451. There is no immediate urgency to upgrade so we can
wait a bit then review if we drop net451 and maybe try to target
netstandard1.4. Thanks for digging out and linking the relevant issues.
I'll keep en eye on them.   Cheers.

On Sat, 18 Feb 2017 at 04:09, Brandon Ording <notifications@github.com>
wrote:

I've spent some time looking into this, and the new tooling does currently
have a regression where they are no longer pulling in mono to be able to
build net451 from non-Windows machines. 😢

dotnet/sdk#335 <https://github.com/dotnet/sdk/issues/335>

I tried out the workaround mentioned here
<https://github.com/dotnet/sdk/issues/335#issuecomment-271186591>, but I
was getting errors about missing types that should have been there, so I'm
guessing the targeting pack nuget is missing some things.

If Microsoft doesn't get this fixed for RTM, and based on the issue it
doesn't look likely, then you'd need to either hold off moving to the new
project system (and VS 2017), or consider dropping net451 and just compile
for netstandard1.5. That would mean you'd be moving the minimum supported
framework to 4.6.1, though. 😢

Another thing that I ran into while playing around with this is that NUnit
does not currently work in the new project system either, so you can't run
tests from inside of VS 2017 or from the command line via dotnet test.

nunit/nunit3-vs-adapter#297
<https://github.com/nunit/nunit3-vs-adapter/issues/297>

Looks like xUnit works just fine already, so maybe it's time to migrate? 😁

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/308#issuecomment-280820163>,
or mute the thread

**Comment by vgotra** [comment] 2017-02-22 00:19
Hi guys - I can also help with .Net Core client for RabbitMq, but for me it's a question - on which implementation of client better to spend a time - on official or on Angora. In official (current) client I matched a lot of old legacy code, and also a lot of Java migrated legacy (interfaces, etc.) - but it can work. About Angora I don't know a lot and also it's a question - is it possible to implement at least 90% of functionality related to official client in Angora.  
In official I see potential improvements which can cause changes to public API interfaces to make it correct from software design point (.Net). 
Will be grateful for your thoughts related to this message and will be happy to help.

**Comment by michaelklishin** [comment] 2017-02-22 00:38
We have announced months ago that we will develop a new .NET client from scratch this year and the existing client is in maintenance mode. There is nothing wrong with helping other clients, though, since we have no plans of starting the work in the next 2-3 months. This is not the right place to discuss this: not only this issue is not about .NET Core support in general, our team does not use GitHub issues for discussions.

**Comment by bording** [comment] 2017-03-07 23:49
@kjnilsson I came across this: https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-rc4#using-net-framework-as-targets-framework-the-osxunix-build-fails

Which talks about another possible way to work around the lack of mono support in the VS 2017 tooling. If the `FrameworkPathOverride` option works, then it would be possible to move forward with this now.

**Comment by kjnilsson** [comment] 2017-03-08 09:25
Ok thanks for finding that. Might be an option although probably falls in the category of horrendous workarounds. :)

**Comment by bording** [comment] 2017-03-08 16:20
> Ok thanks for finding that. Might be an option although probably falls in the category of horrendous workarounds. :)

Totally, but might be worth it until it gets fixed for real! 😀

**Comment by kjnilsson** [comment] 2017-05-15 11:50
Looks like we've hit a snag here with packaging. Although using `msbuild` to build works fine it seems mono 5.0 doesn't include the ["Pack" Sdk[(https://github.com/dotnet/sdk/issues/335#issuecomment-301450271) which means we don't have a ready replacement for our use of `dotnet pack` within our build scripts.  We can look at alternatives perhaps using a nuspec and `nuget` directly or perhaps switch to `paket`. Either way it will be a short term change as ideally we'd like to stay with the dotnet core tooling.

**Comment by adamralph** [comment] 2017-05-15 12:00
nuget.exe + nuspec should still work. I'm still packaging plenty of multi-targetted nuget packages this way, including some that support a version of .NET Standard.

**Comment by kjnilsson** [comment] 2017-05-15 12:03
Just as I wrote the last comment I was advised I could just add the missing msbuild Sdk to the project and this seems to work. Need to do a bit more testing though.

**Comment by danielmarbach** [comment] 2017-09-21 12:03
Is this still relevant with NET Core 2.0 out the door?

**Comment by michaelklishin** [comment] 2017-09-21 15:24
@danielmarbach I tried it on a new machine a few days ago and ran into obscure issues with our build system. So I suspect there is now something else to do and would leave this open until we have evidence of the contrary.

**Comment by kjnilsson** [comment] 2017-09-29 08:46
@danielmarbach is there value in updating to 2.0 at this point? I have to admit I haven't kept up on the changes there.

**Comment by lukebakken** [comment] 2020-01-30 00:32
Our build system is using .NET Core SDK 2.2 & 3.1 without issue, and AppVeyor is working smoothly as well so I will consider this issue to be out-of-date. Thanks everyone.

**Closed by lukebakken** 2020-01-30 00:32 UTC
