### ISSUE TITLE
IsHeadersPreset may return invalid value in some cases

### ISSUE THREAD

**Issue by lcapka** [rabbitmq/rabbitmq-dotnet-client#942] opened 2020-09-15 21:31 UTC
Hi,
there is a bug in the code since version 6.2.1 (probably). The generation of API has been changed and it uses local properties now but there are cases when the property value is inconsistent with the real content. To be specific:

1) The WireFormatting.ReadTable() method may return **null** in the 6.2.1 - that's new. It couldn't in 6.1.0 where it always returned at least empty dictionary. 6.2.1 looks like this:
![image](https://user-images.githubusercontent.com/3823266/93266071-dbf4ab00-f7a9-11ea-842b-94ed809be913.png)

2) The autogenerated file "autogenerated-api-0-9-1.cs" now generates private properties for Is*Preset() methods. Like this:
`public override bool IsHeadersPresent() => _headers_present;`

3) The autogenerated constructor in that file looks like:
![image](https://user-images.githubusercontent.com/3823266/93266400-4a396d80-f7aa-11ea-9473-1b5cb90930fe.png)

The issue in the constructor is that **_headers_present** is set before the value is assigned to the **_headers** property. There is a case when **_headers_present == true** but ReadTable returns **null**. And then IsHeadersPresent() returns true while Headers returns null which isn't expected behaviour.

In the older versions the IsHeadersPresent() method returned **_headers != default** (null). We had to revert to 6.1.0.

Note that the same may apply to other Is*Present() methods. Please review all for the same issue.

Attached auto-generated file from the 6.2.1 source code.
[autogenerated-api-0-9-1.cs.zip](https://github.com/rabbitmq/rabbitmq-dotnet-client/files/5228382/autogenerated-api-0-9-1.cs.zip)

**Comment by michaelklishin** [comment] 2020-09-15 21:34
Thank you for the analysis but I'm still not sure what practical difference does it make. Also, this is open source software so if you understand the problem well, please submit a PR.

**Comment by Pliner** [comment] 2020-09-16 05:38
@michaelklishin The issue came from EasyNetQ.

Previously `IsHeadersPresent` was used to ensure that `headers` are not null and not empty. After 6.2.1 this approach doesn't work anymore.

Here is an example.
https://github.com/EasyNetQ/EasyNetQ/pull/1111/files#diff-40fd02e603503efaa89bbb23bb6ae7d7L44

Without any doubts, this could be fixed inside EasyNetQ. However, the current behaviour makes usage of the client less convenient, moreover `IsHeadersPresent` looks meaningless now because it returns true in case of null headers (:

**Comment by Pliner** [comment] 2020-09-16 06:12
>Previously IsHeadersPresent was used to ensure that headers are not null and not empty. 

But it looks like it was an incorrect expectation and `IsHeadersPresent` was true even if headers were empty 😞

**Comment by michaelklishin** [comment] 2020-09-16 14:18
I'm not arguing that this behavior is unintentional and should be treated as a regression, just don't see this method used a whole lot.

**Closed** 2020-11-17 22:32 UTC

**Comment by stebet** [comment] 2020-11-27 10:23
This is a bit inconvenient as the "IsHeadersPresent" properties mostly apply to internal functionality. I'd actually propose removing them from the next major version since they are mostly there for the wireformatted to determine which presence bits to set when (de)serializing the BasicProperties object.

I'll write up a proposal on this that makes more sense.

**Comment by dlemstra** [comment] 2021-08-05 15:07
It looks like this issue was added to the 6.2.2 milestone but it does not seem to be fixed in that release. Looking at the latest comment it should probably be removed from that milestone.

**Comment by michaelklishin** [comment] 2021-08-06 06:36
@dlemstra "does not seem to be"? Do you have any evidence e.g. of it not being backported to `6.x` in time for `6.2.2`? We do not speculate in this community. The entire .NET client codebase is open source.

**Comment by dlemstra** [comment] 2021-08-06 07:46
We noticed this when upgrading to the latest version. I took a look at the code and the initial problem reported here is still present in `autogenerated-api-0-9-1.cs`.

```C#
_headers_present = reader.ReadPresence();
```

This will set the value to `true` because the headers are present in the `ContentHeader`.

```C#
if (_headers_present) { _headers = reader.ReadTable(); }
```

But `reader.ReadTable()` will return null when there is an empty table. This apparently also breaks the `.Clone` method. That can be reproduced on the 6.x branch with the following unit test:

```C#
var subject = new Framing.BasicProperties // From autogenerated-api-0-9-1.cs
{
    Headers = new Dictionary<string, object>()
};

Span<byte> span = new byte[1024];
var writer = new Impl.ContentHeaderPropertyWriter(span);
subject.WritePropertiesTo(ref writer);

subject.ReadFrom(span);

subject.Clone();
```

Exception thrown:
```console
  Message: 
    System.ArgumentNullException : Value cannot be null.
    Parameter name: dictionary

  Stack Trace: 
    Dictionary`2.ctor(IDictionary`2 dictionary, IEqualityComparer`1 comparer)
    Dictionary`2.ctor(IDictionary`2 dictionary)
    BasicProperties.Clone() line 278
    TestBasicProperties.NamingUnitTestsIsDifficult() line 162
```

A possible fix could be to do this instead:

```C#
if (_headers_present) { Headers = reader.ReadTable(); }
```

That will use the property and set the value of `_headers_present` to `false`.
