### ISSUE TITLE
Depend on Microsoft.Diagnostics.Tracing.EventSource 2.0.0 (requires .NET 4.6.1)

### ISSUE THREAD

**Issue by gewoonjerry** [rabbitmq/rabbitmq-dotnet-client#420] opened 2018-05-14 10:22 UTC
Hello,

We recently updated the NuGet packages in our projects and found an issue with RabbitMQ Client 5.0.1.
It has a reference to Microsoft.Diagnostics.Tracing.EventSource.Redist package which also has been updated recently to version 2.0.0.

Unfortunately RabbitMQ Client 5.0.1 references an older version (1.1.28.0) which, when you upgrade your Redist package to 2.0.0 you'll get the following error in some circumstances: 

The service threw an unhandled exception
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Diagnostics.Tracing.EventSource, Version=1.1.28.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Microsoft.Diagnostics.Tracing.EventSource, Version=1.1.28.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

A solution for now is downgrading to Microsoft.Diagnostics.Tracing.EventSource.Redist version 1.1.28.0 because a binding redirect won't work since the PublicKeyToken has been changed as of version 2.0.0

It would be nice if an upcoming release of the RabbitMQ .Net Client could reference the new Redist assembly.

Kind regards,

Jerry

**Comment by michaelklishin** [comment] 2018-05-14 15:28
Duplicate of #419.

**Comment by bording** [comment] 2018-05-14 15:56
@michaelklishin I'm not sure I'd qualify this as a duplicate of #419, since this issue is a request to move the RabbitMQ client's package dependency to the newer 2.0.0 version of Microsoft.Diagnostics.Tracing.EventSource.Redist instead of keeping it at 1.1.28.

However, it won't be possible to move to 2.0.0 right now because that version of the package has dropped support for older .NET Framework versions and only ships a `net461` assembly.

The RabbitMQ client currently targets `net451`, so the 1.1.28 package has to be used because it includes a `net40` assembly.

**Comment by gewoonjerry** [comment] 2018-05-14 16:13
@bording Exactly my point. A binding redirect mentioned in #419 isn't a viable option either since the public key token is changed in 2.0.0. and i would like to keep al my NuGet packages up tot date.

**Comment by michaelklishin** [comment] 2018-05-14 16:42
We probably can drop .NET 4.5.1 support by 6.0.

**Comment by maxdeviant** [comment] 2018-07-13 19:01
Just ran into this as well.

@gewoonjerry Is there a workaround that you've been using for this issue?

**Comment by gewoonjerry** [comment] 2018-07-13 19:59
@maxdeviant Sadly no, the only thing we did for now is set the allowedVersions in the packages.config so it won't be updated by accident....that...and to stop it front bugging us that there's an update available

**Comment by maxdeviant** [comment] 2018-07-13 20:01
@gewoonjerry I pinned it to the older version in our `paket.dependencies` file and that appears to have fixed the issue.

```
nuget Microsoft.Diagnostics.Tracing.EventSource.Redist ~> 1.1.28.0
```

We don't reference it directly in any of our projects, so I'm just hoping another dependency doesn't want `v2.0` as a dependency 😨

**Comment by michaelklishin** [comment] 2018-07-13 20:04
This has been [discussed to death](https://groups.google.com/d/msg/rabbitmq-users/vqXM0B0m48U/ezPazFBpAwAJ) several times on the mailing list.

We will require .NET 4.6.1 in 6.x which will open more options. Our team does not use GitHub issues for discussions.

**Comment by kjnilsson** [comment] 2018-09-06 10:36
The dependency on Microsoft.Diagnostics.Tracing.EventSource has been removed so I will close this issue now. Thanks.

**Closed by kjnilsson** 2018-09-06 10:36 UTC
