### ISSUE TITLE
Failure in IP address resolution results in numerous end of stream exceptions

### ISSUE THREAD

**Issue by MichaelLogutov** [rabbitmq/rabbitmq-dotnet-client#260] opened 2016-09-22 08:57 UTC
We're facing strange issue with many AMQP errors generated after IP resolve failed.

Basically it goes like this.

Application got unobserved exception (from TaskScheduler.UnobservedTaskException):

```
22.09.2016 06:12:02 | ERROR | Application | A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.ArgumentException: No ip address could be resolved for rabbitmq.msk.cian.ru
   at RabbitMQ.Client.TcpClientAdapter.<ConnectAsync>d__2.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentException: No ip address could be resolved for rabbitmq.msk.cian.ru
   at RabbitMQ.Client.TcpClientAdapter.<ConnectAsync>d__2.MoveNext()<---
```

After that we've got huge amount of errors (multiple per second) like this:

```
22.09.2016 06:12:25 | ERROR | Application | Already closed: The AMQP operation was interrupted: AMQP close-reason, initiated by Library, code=0, text="End of stream", classId=0, methodId=0, cause=System.IO.EndOfStreamException: Heartbeat missing with heartbeat == 2 seconds
RabbitMQ.Client.Exceptions.AlreadyClosedException: Already closed: The AMQP operation was interrupted: AMQP close-reason, initiated by Library, code=0, text="End of stream", classId=0, methodId=0, cause=System.IO.EndOfStreamException: Heartbeat missing with heartbeat == 2 seconds
   at RabbitMQ.Client.Framing.Impl.Connection.EnsureIsOpen()
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.CreateModel()
   at ... (our code)
```

and like this:

```
22.09.2016 06:12:25 | ERROR | Application | Already closed: The AMQP operation was interrupted: AMQP close-reason, initiated by Library, code=0, text="End of stream", classId=0, methodId=0, cause=System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at RabbitMQ.Client.Impl.Frame.ReadFrom(NetworkBinaryReader reader)
   at RabbitMQ.Client.Impl.SocketFrameHandler.ReadFrame()
   at RabbitMQ.Client.Framing.Impl.Connection.MainLoopIteration()
   at RabbitMQ.Client.Framing.Impl.Connection.MainLoop()
RabbitMQ.Client.Exceptions.AlreadyClosedException: Already closed: The AMQP operation was interrupted: AMQP close-reason, initiated by Library, code=0, text="End of stream", classId=0, methodId=0, cause=System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at RabbitMQ.Client.Impl.Frame.ReadFrom(NetworkBinaryReader reader)
   at RabbitMQ.Client.Impl.SocketFrameHandler.ReadFrame()
   at RabbitMQ.Client.Framing.Impl.Connection.MainLoopIteration()
   at RabbitMQ.Client.Framing.Impl.Connection.MainLoop()
   at RabbitMQ.Client.Framing.Impl.Connection.EnsureIsOpen()
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.CreateModel()
   at ... (our code)
```

We've using https://www.nuget.org/packages/RabbitMQ.Client/4.1.1-rc1
.NET 4.6.1

Here's a code for ConnectionFactory (created once per application):

```
var result = new ConnectionFactory();
result.HostName = host;
result.Port = port;
result.UserName = user_name;
result.Password = password;
result.AutomaticRecoveryEnabled = true;
result.TopologyRecoveryEnabled = true;
result.RequestedHeartbeat = 2;
result.NetworkRecoveryInterval = TimeSpan.FromMilliseconds(500);
result.RequestedConnectionTimeout = 1000;
```

Here's a connection (created once per application):

```
var connection = this.connectionFactory.CreateConnection();
connection.AutoClose = false;
```

And he's a channel (created each on publish method call):

```
var channel = connection.CreateModel();
channel.ConfirmSelect();
```

**Comment by kjnilsson** [comment] 2016-09-22 09:01
When does the exception occur? during `CreateConnection`?

**Comment by MichaelLogutov** [comment] 2016-09-22 09:07
First error - unobserved task exception (outside our code).
Other errors - on channel creation (CreateModel)

**Comment by kjnilsson** [comment] 2016-09-22 09:09
what is the setting of this config value?
```
<configuration> 
    <runtime> 
        <ThrowUnobservedTaskExceptions enabled=”true”/> 
    </runtime> 
</configuration>
```

**Comment by MichaelLogutov** [comment] 2016-09-22 09:13
We do not have this option specified in config - so it's by default (I guess it's on).
But we do have a custom handler for those exceptions (which outputs the first error in our log):
```
TaskScheduler.UnobservedTaskException += (sender, args) =>
                                                     {
                                                         this.LogError(args.Exception);
                                                         args.SetObserved();
                                                     };
```

**Comment by kjnilsson** [comment] 2016-09-22 09:14
ok looks like this exception isn't propagating correctly. It should be thrown when the connection is created. I'll take a look at it. Thanks.

**Comment by tasosss** [comment] 2017-08-30 11:42
Hello! I'm having the same problem.But it's not clear to me from what you have written above which is the problem/solution.
[Here](https://groups.google.com/forum/#!topic/rabbitmq-users/Md1pXrNr6G0) is my post on rabbitmq-users.
Thanks!

**Comment by pantonis** [comment] 2018-04-18 08:48
Same problem here.

**Comment by michaelklishin** [comment] 2018-10-24 15:32
We don't have a way to reproduce this and this is from the relatively early days of .NET Core migration. Closing.

**Comment by michaelklishin** [comment] 2018-10-24 15:33
By the way, there were changes around socket activity and consumer operation dispatch in recent (5.x) releases.

**Closed by michaelklishin** 2018-10-24 15:32 UTC

**Comment by senglory** [comment] 2021-01-13 15:47
Hi guys, I am experiencing exactly the same issue with RabbitMQ client v6.2.1 in my .NET Core 3.0 app. Many queues are consumed flawlessly but two to be used for sending messages throw this weird "No ip address could be resolved for XXX" even if I point a direct IP address instead of XXX. What's wrong with my ConnectionFactory definition? I don't work with Ipv6, it's 100% for sure. the failure happens on the last line in this code:

```
            System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
            ConnectionFactory connectionFactory = new ConnectionFactory
            {
                AutomaticRecoveryEnabled = true,
                NetworkRecoveryInterval = new TimeSpan(0, 0, 0, 0, settings.NetworkRecoveryIntervalInMs),
                HostName = settings.Host,
                TopologyRecoveryEnabled = true,
                Ssl = settings.UseSSL ? new SslOption
                {
                    Enabled = true,
                    Version = System.Security.Authentication.SslProtocols.Tls12,
                    ServerName = settings.Host,
                    CertPath = settings.Cert,
                    CertPassphrase = settings.CertPassphrase,
                    AcceptablePolicyErrors = SslPolicyErrors.RemoteCertificateNameMismatch | SslPolicyErrors.RemoteCertificateChainErrors
                } : null,
                VirtualHost = settings.VirtualHost,
                Port = int.Parse(settings.Port),
                UserName = settings.UserName,
                Password = settings.Password
            };

            return connectionFactory.CreateConnection(settings.ClientName);
```
