### ISSUE TITLE
ConnectionFactory.CreateConnection() fails when using a custom port

### ISSUE THREAD

**Issue by whvanderpost** [rabbitmq/rabbitmq-dotnet-client#209] opened 2016-06-16 17:26 UTC
After we upgraded to version 3.6.2 of the NuGet package a problem appeared. We use a custom port to connect to RabbitMQ by using the following code (simplified):
`var cf = new ConnectionFactory();`
`cf.HostName = "localhost";`
`cf.Port = 12345;`
`cf.VirtualHost = "vHost1";`
`_connection = cf.CreateConnection();`

At the CreateConnection call we get a BrokerUnreachableException with the message "Additional information: None of the specified endpoints were reachable".
The innerexception tells me "No connection could be made because the target machine actively refused it 127.0.0.1:5672". Which makes sense, since I've changed the port of RabbitMQ. But doesn't make sense since I've told the ConnectionFactory to use a different port.

I've downgraded to 3.6.1 and it all worked again as expected.

Did something change in the API? Do we have to update our code?

**Comment by kjnilsson** [comment] 2016-06-16 17:58
There is a bug in the ConnectionFactory in 3.6.2. If you use a custom port
use 3.6.1 until 3.6.3 is released.

Cheers
Karl

**Comment by michaelklishin** [comment] 2016-06-16 18:51
Duplicate of https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/186.

**Closed by michaelklishin** 2016-06-16 18:51 UTC
