### ISSUE TITLE
AutoReconnect may generate hundreds of connections

### ISSUE THREAD

**Issue by manuelspezzani** [rabbitmq/rabbitmq-dotnet-client#1093] opened 2021-09-28 08:49 UTC
Repro:
1. declare a non-durable exchange from the management ui
2. from a test application, bind an anonymous queue to the exchange without declaring the exchange
3. restart rabbit

As soon as the broker is up and running, the client starts creating more and more connections actually "killing" rabbit.

From what I can tell, this is caused by the fact that on each autoreconnect retry the client is able to establish a connection but constantly fails to reinitialize the bindings (because the exchange doesn't exists anymore). 
What's happening is perfectly fine IMHO: of course the autoreconnect will never be able to succeed. But the fact that the client is creating more and more connections without closing the existing ones sounds like a bug to me: it's going to be extremely easy to kill a rabbitmq instance that way... 

I'm on RabbitMQ.Client version 6.2.2. 

NOTE: 
Step 1 is just a convenient way to consistently "break" the autoreconnect capability, I guess there may be many more more convoluted ways to achieve the same result...

**Comment by michaelklishin** [comment] 2021-09-28 09:27
Duplicate of #1061 (or at least that's highly likely).

**Closed by michaelklishin** 2021-09-28 09:27 UTC
