### ISSUE TITLE
Short frame - expected 131064 bytes, got n bytes

### ISSUE THREAD

**Issue by skubi** [rabbitmq/rabbitmq-dotnet-client#199] opened 2016-06-09 11:25 UTC
Hello,

I am facing very strange behavior and unfortunately cannot find any rational explanation to it.
I am consuming messages from the queue with the service and at some point I am starting to get following exception:

```
Connection shutdown requested. Reason: AMQP close-reason, initiated by Library, code=501, text="Short frame - expected 131064 bytes, got 127561 bytes", classId=0, methodId=0, cause=RabbitMQ.Client.Impl.MalformedFrameException: Short frame - expected 131064 bytes, got 127561 bytes
   at RabbitMQ.Client.Impl.Frame.ReadFrom(NetworkBinaryReader reader)
   at RabbitMQ.Client.Impl.SocketFrameHandler.ReadFrame()
   at RabbitMQ.Client.Framing.Impl.Connection.MainLoopIteration()
   at RabbitMQ.Client.Framing.Impl.Connection.MainLoop()
```

This is happening with any message from the queue starting from some point of the time (could run for weeks without the problems). The exception is always like:

```
Short frame - expected 131064 bytes, got n bytes
```

Where n is any amount of bytes message actually contains of. 
131064 bytes is  [default value of frame_max](https://www.rabbitmq.com/configure.html)

From RabbitMQ instance logs:

```
--
=INFO REPORT==== 6-Jun-2016::10:20:47 ===
accepting AMQP connection <0.8031.7> (10.xxx.xxx.xx:53256 -> 10.xxx.xxx.xx:5672)
--
=ERROR REPORT==== 6-Jun-2016::10:21:17 ===
closing AMQP connection <0.8031.7> (10.xxx.xxx.xx:53256 -> 10.xxx.xxx.xx:5672):
{writer,send_failed,{error,timeout}}
```

Restarting both RabbitMQ instance and RabbitMQ host didn't help. 
I am using EventingBasicConsumer at the moment but switching to the blocking one didn't fix the issue, too. I am using autorecovery connection and autorecovery model with both AutomaticRecoveryEnabled and TopologyRecoveryEnabled set to true.

RabbitMQ 3.6.1, Erlang R16B03
RabbitMQ.Client 3.6.1

Tested against RabbitMQ.Client version 3.6.1 and 3.6.2

Implementation is really simple and basic:

``` csharp
    using System;
    using RabbitMQ.Client;
    using Settings;

    public class ConnectionFactoryFactory : IConnectionFactoryFactory
    {
        public ConnectionFactory CreateConnectionFactory(string user, string password,
                                                         IProtocol protocol,
                                                         string host, int port,
                                                         int timeoutInMs = 60000)
        {
            return new ConnectionFactory
            {
                UserName = user,
                Password = password,

                Protocol = protocol,
                HostName = host,
                Port = port,

                RequestedConnectionTimeout = timeoutInMs,
                SocketReadTimeout = timeoutInMs,
                SocketWriteTimeout = timeoutInMs,

                AutomaticRecoveryEnabled = true,
                TopologyRecoveryEnabled = true,
                NetworkRecoveryInterval = TimeSpan.FromSeconds(5),
                RequestedHeartbeat = 120,
                UseBackgroundThreadsForIO = true
            };
        }
    }                                                                                                                          ;
```

``` csharp
    using RabbitMQ.Client;
    using RabbitMQ.Client.Events;
    using RabbitMQ.Client.Framing.Impl;

    public class AutorecoveringConnectionFactory : IAutorecoveringConnectionFactory
    {
        private IConnectionFactoryFactory ConnectionFactoryFactory { get; }

        public AutorecoveringConnectionFactory(IConnectionFactoryFactory connectionFactoryFactory)
        {
            ConnectionFactoryFactory = connectionFactoryFactory;
        }

        public AutorecoveringConnection CreateAutorecoveringConnection(string user, string password,
                                                                       IProtocol protocol,
                                                                       string host, int port,
                                                                       int timeoutInMs = 60000)
        {
            var factory = ConnectionFactoryFactory.CreateConnectionFactory(user, password, protocol,
                host, port, timeoutInMs);

            var autorecoveringConnection = (AutorecoveringConnection)factory.CreateConnection();
            autorecoveringConnection.CallbackException += (s, args) => ConnectionCallbackExceptionHandler(args);
            autorecoveringConnection.ConnectionBlocked += (s, args) => ConnectionBlockedHandler(args);
            autorecoveringConnection.ConnectionShutdown += (s, args) => ConnectionShutdownHandler(args);
            autorecoveringConnection.ConnectionUnblocked += (s, args) => ConnectionUnblockedHandler();
            autorecoveringConnection.Recovery += (s, args) => ConnectionRecoveryHandler();

            return autorecoveringConnection;
        }
    }
```

``` csharp
    using RabbitMQ.Client;
    using RabbitMQ.Client.Events;

    public class ModelFactory : IModelFactory
    {
        public IModel CreateModel(IConnection connection)
        {
            var model = connection.CreateModel();

            model.BasicAcks += (s, args) => ModelBasicAcksHandler(args);
            model.BasicNacks += (s, args) => ModelBasicNacksHandler(args);
            model.BasicRecoverOk += (s, args) => ModelBasicRecoverOkHandler();
            model.BasicReturn += (s, args) => ModelBasicReturnHandler(args);

            model.CallbackException += ModelCallbackExceptionHandler;
            model.ModelShutdown += ModelShutdownHandler;

            model.BasicQos(0, 200, false);
            return model;
        }
    }
```

``` csharp
    using System;
    using RabbitMQ.Client;
    using RabbitMQ.Client.Events;

    public class EventingConsumerFactory : IEventingConsumerFactory
    {
        public EventingBasicConsumer CreateConsumer(IModel model,
                                                    EventHandler<BasicDeliverEventArgs> recievedEventHandler)
        {
            var consumer = new EventingBasicConsumer(model);
            consumer.Received += recievedEventHandler;
            consumer.Registered += (s, e) => ConsumerRegisteredHandler(e);
            consumer.Shutdown += ConsumerShutdownHandler;
            consumer.Unregistered += (s, e) => ConsumerUnregisteredHandler(e);
            consumer.ConsumerCancelled += (s, e) => ConsumerCancelledHandler(e);
            return consumer;
        }
    }
```

And consumer itself:

``` csharp
    using System;
    using System.Threading;
    using System.Threading.Tasks;
    using Exceptions;
    using Factories;
    using RabbitMq.Gateway;
    using RabbitMq.Gateway.Data;
    using RabbitMQ.Client;
    using RabbitMQ.Client.Events;
    using Settings;

    public class EventingAutobindingConsumer : IDisposable
    {
        private IAutorecoveringConnectionFactory AutorecoveringConnectionFactory { get; }
        private IModelFactory ModelFactory { get; }
        private IEventingConsumerFactory EventingConsumerFactory { get; }
        private IMessageConsumer MessageConsumer { get; }

        private BusConnectionSettings Settings { get; }

        private string ConsumerTag { get; set; }

        private IConnection Connection { get; set; }
        private IModel Model { get; set; }

        public EventingAutobindingConsumer(IAutorecoveringConnectionFactory autorecoveringConnectionFactory,
                                           IModelFactory modelFactory,
                                           IEventingConsumerFactory eventingConsumerFactory,
                                           IMessageConsumer messageConsumer,
                                           BusConnectionSettings settings)
        {
            AutorecoveringConnectionFactory = autorecoveringConnectionFactory;
            ModelFactory = modelFactory;
            EventingConsumerFactory = eventingConsumerFactory;
            MessageConsumer = messageConsumer;
            Settings = settings;
        }

        public async Task StartConsumingAsync(CancellationToken token)
           => await Task.Run(() => StartConsuming(token), token);

        private void StartConsuming(CancellationToken token)
        {
            if(Settings == null)
                throw new ConfigurationMissingException();

            var autorecoveringConnection =
                AutorecoveringConnectionFactory.CreateAutorecoveringConnection(Settings.Username,
                    Settings.Password, Settings.Protocol, Settings.HostName, Settings.Port);

            autorecoveringConnection.ConsumerTagChangeAfterRecovery += (sender, args) =>
                ConsumerTagChangeAfterRecoveryHandler(args);
            autorecoveringConnection.QueueNameChangeAfterRecovery += (sender, args) =>
                QueueNameChangeAfterRecoveryHandler(args);

            var model = ModelFactory.CreateModel(autorecoveringConnection);
            var eventingConsumer = EventingConsumerFactory.CreateConsumer(model,
                (sender, args) => ConsumerRecievedHandler((EventingBasicConsumer)sender, args, token));

            Model = model;
            Connection = autorecoveringConnection;
            ConsumerTag = model.BasicConsume(Settings.Queue, false, eventingConsumer);
        }

        private async void ConsumerRecievedHandler(IBasicConsumer consumer, BasicDeliverEventArgs args, CancellationToken token)
        {
            try
            {
                var success = await MessageConsumer.Consume(args, token);
                if (success)
                    consumer.Model.BasicAck(args.DeliveryTag, false);
                else
                    consumer.Model.BasicReject(args.DeliveryTag, !args.Redelivered);
            }
            catch (Exception exception)
            {
                if (consumer.Model.IsOpen)
                    consumer.Model.BasicReject(args.DeliveryTag, !args.Redelivered);
            }
        }

        public void StopConsuming()
        {
            Model?.Abort();
            Connection?.Abort();
        }

        public void Dispose()
        {
            Model?.Dispose();
            Connection?.Dispose();
        }
```

I omitted some extra parts like handlers and logging as they don't seem to be relevant to the issue.
Our setup looks like this:

Azure VM -> Azure LB -> HA Proxy (2 instances loadbalanced) -> RabbitMQ primary node

I am not actually sure if this is the issue with RabbitMQ.Client, but this was the proposal from  [ Google groups](https://groups.google.com/forum/#!topic/rabbitmq-users/38aFbJt_7zY) to turn to you.
Thanks!

**Comment by kjnilsson** [comment] 2016-06-13 07:18
Just to clarify does your connection go through two load balancers before it reaches a rabbit node? If so is there anything in the Azure LB or HA Proxy logs that could provide some more info?

**Comment by skubi** [comment] 2016-06-13 07:53
Yes, connection goes through two LBs before reaching the node. Azure LB balancing between two HA Proxy instances, but both HA Proxy instances are pointing to the same RabbitMQ node for now. Azure LB uses session stickiness (source IP distribution policy).

Unfortunately we cannot retrieve logs from Azure for their LB directly, but we are in communication with them to get at least some logs eventually.

HAProxy logs look like this (doesn't look much useful):

```
Jun 13 07:42:46 HAPROXYNAME haproxy[1047]: Connect from xxx.xx.xxx.xx:52712 to xxx.xx.xxx.xx:5672 (rabbitmq/TCP)
Jun 13 07:42:48 HAPROXYNAME haproxy[1047]: Connect from xxx.xx.xxx.xx:52719 to xxx.xx.xxx.xx:5673 (rabbitmq2/TCP)
Jun 13 07:42:51 HAPROXYNAME haproxy[1047]: Connect from xxx.xx.xxx.xx:52803 to xxx.xx.xxx.xx:5672 (rabbitmq/TCP)
Jun 13 07:42:53 HAPROXYNAME haproxy[1047]: Connect from xxx.xx.xxx.xx:52855 to xxx.xx.xxx.xx:5673 (rabbitmq2/TCP)
Jun 13 07:42:56 HAPROXYNAME haproxy[1047]: Connect from xxx.xx.xxx.xx:62853 to xxx.xx.xxx.xx:5672 (rabbitmq/TCP)
Jun 13 07:42:59 HAPROXYNAME haproxy[1047]: Connect from xxx.xx.xxx.xx:62887 to xxx.xx.xxx.xx:5673 (rabbitmq2/TCP)
Jun 13 07:43:01 HAPROXYNAME haproxy[1047]: Connect from xxx.xx.xxx.xx:62942 to xxx.xx.xxx.xx:5672 (rabbitmq/TCP)
```

etc. without any errors.

**Comment by kjnilsson** [comment] 2016-06-13 09:34
Ok having taken a brief look at the code I think it warrants some further investigation. There may be something better we can do for the case when a read returns fewer bytes than expected.

**Comment by kjnilsson** [comment] 2016-11-04 10:03
@skubi are you still experiencing the same issues? I have done a fairly thorough review of the client and the socket code itself does what it needs to do in order to read data fully from the socket. I suspect that your problems are due to the complexities of using two load-balancers in between the rabbit server and the client. Every component in between can introduce unreliabilities and strange behaviours that often aren't easy to predict. In your case client should only get into that position when it encounters a genuine end of stream. This could possibly happen when the connection between load balancers was temporarily interrupted.

Do you need both load balancers in between the server and client?

**Comment by skubi** [comment] 2016-11-06 10:58
@kjnilsson yes, unfortunately I am still experiencing the same issue. Well, I would totally agree with you if this issue would be reproducible occasionally, but for me at some point it starts to occur for every single message consumed. As I have already mentioned in my initial post:

> This is happening with any message from the queue starting from some point of the time (could run for weeks without the problems).

I am running such setup with two load balancers for quite a long period of the time for now and unfortunately this is necessary measure in my use case. In general I do need HAProxy for having active-passive type of replication against multiple RabbitMQ nodes. Using multiple HAProxy instances is the matter of reliability, and achieving desired latencies on very high loads. What might be another option achieving requirements mentioned?

**Comment by kjnilsson** [comment] 2016-11-07 16:09
@skubi I suspect it is very likely that the issue stems from the interactions between your load balancers and the server. As suggested before I think you should get the logs from all your load balancers and see what is going on at the time the issue appears. TCP traffic (wireshark or tcpdump) captures between each component may also help to determine at what point things get delayed/lost.

When the issue occurs - what do you need to do to recover? You said above that restart the rabbit server (and clients?) did not help?

The rabbitmq-users user group is a good place to discuss configuration and infrastructure options. It is hard for me to evaluate your exact requirements.

**Comment by skubi** [comment] 2016-11-08 05:32
@kjnilsson yes, sure, sorry for the confusion, I did not mean to start infrastructural discussion here in this thread and on GitHub in general. I was trying to point out that in general setup seems pretty reasonable for me.

When the issue occurs we need to purge the queue (or move the messages away and then back to the queue). 

Unfortunately it seems not possible to get any logs from Azure load balancers. At least I did not succeed to do that after that amount of the time in communication with Azure support. I will take a look what we I can do more about it.

As @michaelklishin was able to reproduce this issue with dropping packets with firewall could it be useful for client to make exception thrown a bit more descriptive? So far it seems that error message is not exactly reflecting what is happening (if we assume that our conclusion is correct and the error is caused by connection being interrupted at some point):

> Short frame - expected 131064 bytes, got n bytes

**Comment by kjnilsson** [comment] 2016-11-10 16:30
@skubi I initially thought I had reproduced the issue but I was mistaken which is what Michael was referring to above. So to clarify, we have _not_ been able to reproduce. At this stage only traffic captures would provide enough data to continue looking into this as a potential bug. 

I am still confused about your recovery approach. So to recover you don't restart anything, you just purge the queues with the broker and LBs still running?

**Comment by skubi** [comment] 2016-11-11 11:51
@kjnilsson ah, alright, so the issue was not reproduces after all. 

Yes, restarting everything involved (HAProxies, RabbitMQ nodes, hosts where RabbitMQ nodes are deployed to, consuming service, host where consuming service is deployed to, except LB as you cannot restart them in Azure, but only recreate which I have tried, too) does not help to recover at all unless you really purge messages (or move them away). I ended up really not restarting anything but just removing messages from the queue as a temporary workaround for our staging environments and it helps for time being. Quite undesired though.

Well, I think we could close current ticket as you are convinced that it is infrastructural problem. We could get back to this when either I will have more information or there are going to be other signs it is related to client. I will continue investigation myself. Thanks a lot for your time!

**Comment by kjnilsson** [comment] 2016-11-11 11:55
That all sounds very odd to me. I cannot see how re-queueing messages would solve what sounds like a tcp infrastructure issue.

**Comment by michaelklishin** [comment] 2016-11-11 12:05
Wiping out all messages would stop a stream of deliveries to consumers.

**Comment by JocPelletier** [comment] 2018-02-05 18:40
I'm experiencing this issue at one of my installations. My RabbitMQ client is running on a really slow internet connection (Satellite) and I'm trying to transfer a large message (4.4MB) to it. 

On the server side I have `{inet_error,timeout} error` and my client is showing this shutdown error: `Short frame - expected 131064 bytes, got 51146 bytes`

**Comment by michaelklishin** [comment] 2018-02-05 19:53
@JocPelletier `{inet_error,timeout} error` means that the server detected a TCP socket operation timeout. The client message says that it expected to read so many bytes but only read about 51K (most likely due to the same cause: connection instability). Neither client nor server cannot do much about it. Bumping socket operation timeouts on both ends might help temporarily but I doubt it.

Please post your questions to rabbitmq-users in the future. Our team does not use GitHub issues for questions, investigations or discussions.

**Comment by michaelklishin** [comment] 2018-02-05 19:53
No reliable way to reproduce this emerged in well over a year => closing.

**Closed by michaelklishin** 2018-02-05 19:53 UTC
Labels: bug, effort-low

**Comment by michaelklishin** [comment] 2018-02-05 20:15
Relevant doc guides here are:

 * [Heartbeats](https://www.rabbitmq.com/heartbeats.html)
 * [Connection Recovery in .NET client](http://www.rabbitmq.com/dotnet-api-guide.html#connection-recovery)
 * [Networking](https://www.rabbitmq.com/networking.html)
 * [Network Troubleshooting](https://www.rabbitmq.com/troubleshooting-networking.html)
 * [Publisher Confirms and Consumer Acknowledgements](http://www.rabbitmq.com/confirms.html)

.NET client allows for socket [read and write timeout tuning](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/master/projects/client/RabbitMQ.Client/src/client/api/ConnectionFactory.cs#L230).

RabbitMQ server allows for socket timeout tuning via the `tcp_listen_options.send_timeout` option (or `rabbit.tcp_listen_options.send_timeout` in the classic config format).

It is wise to assume that bumping timeouts won't help much but detecting unresponsive peers with a reasonably low heartbeat value (e.g. 5-10 seconds) and performing connection recovery has a chance even on satellite networks.

**Comment by jwillmer** [comment] 2021-02-17 11:24
@JocPelletier did you found a fix for your issue? I'm facing exactly the same issue: Satellite connection and a file size of 4-6MB

**Comment by JocPelletier** [comment] 2021-02-17 11:50
@jwillmer We are only using very small messages now, and for large files, we send a message with file url and the client download it

**Comment by jwillmer** [comment] 2021-02-17 11:57
@JocPelletier O.K., good to know. We investigate a files sync via torrent to transfer large data (files).

**Comment by JocPelletier** [comment] 2021-02-17 12:02
@jwillmer If you have not tested it yet, try to reduce the mtu size on your client to something like 1200. On satellite / cellular connection using the default 1500 seems to cause issue on many systems

**Comment by jwillmer** [comment] 2021-02-17 15:14
@JocPelletier can this be set on RabbitMQ server or does I need to find and set it in the (.NET) client SDK?

**Comment by jwillmer** [comment] 2021-02-17 15:46
@JocPelletier In .NET the frame max is set to 131072 byte (~ 130kb). Are you also referring to byte?
![image](https://user-images.githubusercontent.com/1503577/108228769-76815d80-713f-11eb-9c05-952f0f101a87.png)

**Comment by JocPelletier** [comment] 2021-02-17 15:50
@jwillmer  this is a setting on your network interface, for example in linux: `ip link set enp3s0 mtu 1200` where enp3s0 is the name of the network interface

**Comment by jwillmer** [comment] 2021-02-17 20:48
@JocPelletier O.K., will try that. thank you!
